version: '3'

services:
  minio:
    build: minio
    image: thexia/minio:RELEASE.2023-07-11T21-29-34Z
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=accesskey
      - MINIO_ROOT_PASSWORD=secretkey
      - MINIO_DEFAULT_BUCKETS=hive
    volumes:
      - minio:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped

  mysqldb:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - mysql-for-hive:/var/lib/mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=123456

  hive-metastore:
    build: hive-metastore
    image: thexia/hive-metastore:3.1.2
    ports:
      - 9083:9083
    environment:
      - SERVICE_NAME=metastore
      - IS_RESUME=true
    volumes:
      - ./hive-metastore/conf:/opt/hive/conf
    depends_on: 
      - mysqldb
    restart: unless-stopped

  hive-server:
    build: hive-server
    image: thexia/hive-server:3.1.2
    ports:
      - 10000:10000
      - 10002:10002
    environment:
      - SERVICE_NAME=hiveserver2
      - IS_RESUME=true
    volumes:
      - ./hive-server/conf:/opt/hive/conf
    depends_on:
      - hive-metastore
      - minio
    restart: unless-stopped

volumes:
  minio:
  mysql-for-hive:
    
networks:
  default:
    # 因为thrift协议中不允许下划线，而compose自动为组件生成的domain name为hostname.networkname, networkname为当前dir + '_default'
    name: bigdata